name: Test and Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Java ${{ matrix.java }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: |
          mvn clean install -DskipTests -B
          mvn verify -B
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
      - name: Publish to Apache Maven Central
        run: mvn clean deploy -Drelease -DskipTests -B
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PWD }}

