name: Test and Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Java ${{ matrix.java }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: |
          mvn clean install -DskipTests -B
          mvn verify -B
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
          settings-path: ${{ github.workspace }}
      - name: Publish to Apache Maven Central
        run: mvn clean deploy -Drelease -s $GITHUB_WORKSPACE/settings.xml -DskipTests -B
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PWD: ${{ secrets.BINTRAY_PWD }}

